# 机器人形状
max_obstacle_height: 1.0  # 机器人高度
#robot_radius: 0.25  # 若为圆形，则为机器人半径
footprint: [[0.3, 0.4], [0.3, -0.4],[-0.3, -0.4] ,[-0.3, 0.4]]

map_type: voxel

#图层配置
obstacles:
  enabled:              true
  max_obstacle_height:  1.0
  origin_z:             0.0
  z_resolution:         0.1
  z_voxels:             22
  unknown_threshold:    15    #
  mark_threshold:       0     #
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 2.5           #检测障碍物的最大范围（m）
  raytrace_range: 3.0           #检测自由空间的最大范围（m）
  publish_voxel_map: true
  observation_sources:  scan    #避障需要关注的传感器数据
  scan:
    sensor_frame: laser_link
    data_type: LaserScan
    topic: scan
    marking: true     #是否用传感器实时信息添加代价地图障碍物信息
    clearing: true    #是否用传感器实时信息清除代价地图障碍物信息
    min_obstacle_height: 0.1
    max_obstacle_height: 0.3

inflation_layer:
  enabled:              true
  cost_scaling_factor:  3.0  # 障碍物成本下降的指数速率 (default: 10)
  inflation_radius:     1.0  # 在此离障碍物此距离内，会计算路径成本

static_layer:
  enabled:              true
