global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint

   update_frequency: 2.0
   publish_frequency: 0.5
   transform_tolerance: 0.5       #允许的tf延迟（秒）

   static_map: true
   rolling_window: false          #是否允许是使用rolling window版本的代价地图，在static_map为true时必须设置为false
   always_send_full_costmap: false  #若false，则每次只发布有改变的区域

   #width: 10  #地图宽度（米），默认10
   #height: 10 #地图高度（米），默认10
   #resolution: 0.05   #分辨率（米/cell），默认0.05
   #origin_x: 0.0    #全局坐标系下的x原点位置（米），默认0.0
   #origin_y: 0.0    #全局坐标系下的y原点位置（米），默认0.0
   
   plugins:                       #添加图层，这里的type是costmap_2d已经提供的插件
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacles,             type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

